### ISSUE TITLE
Data invoeren in database via code

### ISSUE THREAD

**Issue by stephandp** [2014-OO3/Resort#10]
Weet er iemand waar precies in de code de sql commando's staan? 
Of hoe je via code gegevens in de database schrijft?

**Comment by luc-steffens-2014** [comment]
@stephandp 
Je kan de customers gewoon aanmaken zoals de bungalows en de parken in de init-db.
Goed idee om daar aparte methodes voor het aanmaken van de parken en de bungalows. Hierbij een voorbeeld voor de customers

@KarlienDeSchutter Ik maak een nieuwe issue aan om daar het antwoord op te geven

```java
 public void createCustomers() {

        List<Object> objectsToSave = new LinkedList<>();

        CustomerEntity customerEntity = new CustomerEntity();
        customerEntity.setFirstName("Jos");
        customerEntity.setLastName("Verstraeten");
        objectsToSave.add(customerEntity);

        for (Object objectsToSave1 : objectsToSave) {
            em.persist(objectsToSave1);
        }
    }
```

**Comment by stephandp** [comment]
oei. hadden het al gevonden!  Was alleen de issue vergeten sluiten.  groeten

Verzonden vanaf Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: luc-steffens-2014 <notifications@github.com>
Datum:01-01-2015  16:14  (GMT+01:00)
Aan: 2014-OO3/Resort <Resort@noreply.github.com>
Cc: stephandp <stephandeplucker@hotmail.com>
Onderwerp: Re: [Resort] Data invoeren in database via code (#10)

@stephandp
Je kan de customers gewoon aanmaken zoals de bungalows en de parken in de init-db.
Goed idee om daar aparte methodes voor het aanmaken van de parken en de bungalows. Hierbij een voorbeeld voor de customers

@KarlienDeSchutter Ik maak een nieuwe issue aan om daar het antwoord op te geven

```java
 public void createCustomers() {

        List<Object> objectsToSave = new LinkedList<>();

        CustomerEntity customerEntity = new CustomerEntity();
        customerEntity.setFirstName("Jos");
        customerEntity.setLastName("Verstraeten");
        objectsToSave.add(customerEntity);

        for (Object objectsToSave1 : objectsToSave) {
            em.persist(objectsToSave1);
        }
    }
```

---
