### ISSUE TITLE
Aanroepen createDB lukt niet

### ISSUE THREAD

**Issue by luc-steffens-2014** [2014-OO3/Resort#11]
@KarlienDeSchutter 

bij mij lukt het maar niet om via init-db een park of een bungalow in mijn database te steken... via mij applicatie zelf lukt het wel, maar waar en hoe moet je de methode "createDB()" aanroepen?

**Comment by luc-steffens-2014** [comment]
Voor het oproepen van de create-db kan ja naar volgende url gaan:

http://localhost:8080/ResortUI/rest/init-db

Je kan ook op deze url geraken door in netbeans in het project onder RESTful Web Services
rechts-klikken op initDBRest en "Test resource URI"

Let wel op dat de applicatie moet draaien voor deze kan werken.

**Comment by KarlienDeSchutter** [comment]
alles werkt joepie
