### ISSUE TITLE
Uurregeling.

### ISSUE THREAD

**Issue by stephandp** [2014-OO3/Resort#12]
Beste, 

Onze beste wensen alvast voor het nieuwe jaar!

Kan u de uurregeling nog eens posten op toledo?

Groeten
Stephan

**Comment by luc-steffens-2014** [comment]
Staan zodadelijk ook op toledo, dit is copy paste uit excel

Normaal moeten jullie geen PC meenemen, ik check de branch uit en jullie moeten hierbij een kleine demo geven. Zeggen wat al dan niet werkt en daarna een aantal vragen beantwoorden.


09:20	Thomas Smet	Arne Polfliet	Lore Van Achter	TheMuskateer
09:40	Stephan De Plucker	Quinten Dockx		DreamTeam
10:00				
10:20	Nico Franckx	Jasper Loverie		Z
10:40	Ben Colson	Gunther Van kelst		GuntherBen
11:00	Kristof Segers	Tom Ver Donck		JavaCoffeeBeans
11:20				
11:40	Marnix Van Lint	Raf Portael		Awesome
12:00				
12:20	Alexander Hermans	Jeroen Van Wauwe	Hamed Majidi Fakr 	DancingForCodepl0x
13:00				
13:20	Elias Serneels	Timothy …	Pieter Drijkoningen	TeamJavagangstazz
13:40	Pepijn Mores	Elliot Braekeleire	Jeroen De Wolf	PEJ
14:00	Olivier Van de Perre	Arnout Vervloet		TeamOreo
14:20				
14:40	Mathias Gooris	Mukhran Beridze	Karlien De Schutter	Koekjes
15:00	Jasper Mariën	Joris Peeters		Jaris
15:20	Shari Maes	Kevin Fort	Davy Smet	TeamShari
15:40				
16:00	Stijn Zwaenepoel	Nicolas De Rechter		DRZ
16:30	Steemans Django			
16:30	Van Rillear Philippe			
16:30	Van Wauwe Jeroen

**Comment by stephandp** [comment]
Super, Bedankt!
