### ISSUE TITLE
NullPointerException bij het laden van parken in een dropdownlist

### ISSUE THREAD

**Issue by stephandp** [2014-OO3/Resort#14]
Beste

Wanneer ik en Quinten onze parken willen tonen op de bungalow.xhtml hebben we zoals eerder hier vernoemd een linkedlist aangemaakt en roepen dan de ListAll op via de ParkDao.
Echter krijgen we hier een NullPointerException op.
Kan u even kijken aub?
Ons team is:
version-DreamTeam

Met vriendelijke groeten
Stephan

**Comment by KarlienDeSchutter** [comment]
bij ons (TeamKoekjes) werkt dat al..
kijk eens voor inspiratie?

**Comment by stephandp** [comment]
Was @EJB vergeten!
thx @KarlienDeSchutter
