### ISSUE TITLE
NullConverter probleem bij het toevoegen van park aan bungalow

### ISSUE THREAD

**Issue by QDockx** [2014-OO3/Resort#15]
Beste

wanneer ik een Bungalow aan een park probeer toe te voegen krijg ik de volgende foutcode:
![image](https://cloud.githubusercontent.com/assets/9860712/5628565/5d7ac952-95a9-11e4-8deb-18a76a728e23.png)

Ons team is DreamTeam.

groeten

**Comment by luc-steffens-2014** [comment]
Is de versie op github?

In de code die ik zie in de changePark-methode in de controller zie ik dat je in de bungalows gaat zoeken achter het park.. 

Nog een kleine belangrijke opmerking. Vergeet je code niet te formateren! Je kan zelf de format gemakkelijk uitvoeren door verschillende bestanden te selecteren en Source > Format te doen.

**Comment by stephandp** [comment]
Beste,

ja de code is op github. 
En inderdaad de format moeten we nog doen maar dat is voor op het laatste moment.
Echter gebruiken we de changePark methode niet. Maar wanneer we de ID van het park willen toevoegen in onze Database wil hij niks toevoegen.

groeten

**Comment by stephandp** [comment]
Beste

Oké heb mijn fout gevonden, was een fout in mijn bungalow.xhtml
