### ISSUE TITLE
Browser opent niet bij het runnen van programma

### ISSUE THREAD

**Issue by h4x0rpr0** [2014-OO3/Resort#16]
Glassfish error:

Severe:   Exception while preparing the app : [PersistenceUnit: RESORTPU] Unable to build Hibernate SessionFactory
org.hibernate.MappingException: Could not determine type for: org.thomasmore.oo3.course.resortui.entity.ParkEntity, at table: bungalow, for columns: [org.hibernate.mapping.Column(parkEntity)]

**Comment by stephandp** [comment]
Dit is een fout op je link tussen je tabellen ;-)

**Comment by h4x0rpr0** [comment]
Mja euhm, op aanraden van iemand heb ik mijn tabellen verwijderd en deze zou ik terugkrijgen als ik pullde maar dat is niet het geval. Hoe los ik dat op?

**Comment by stephandp** [comment]
Je moet dan terug je links verwijderen.

**Comment by luc-steffens-2014** [comment]
Je hebt de ID en de Entiteit gemapped.

https://github.com/2014-OO3/Resort/blob/version-dancing-for-code-pl0x/ResortUI/src/main/java/org/thomasmore/oo3/course/resortui/entity/BungalowEntity.java

Voor het gemak en het jou niet te moeilijk maken mag je gewoon de id houden. Wanneer je de bungalow laad, kan je wanneer nodig het park ook inladen. Dit is niet de optimale manier, maar dit is geen probleem in het kader van deze opgave. We hebben helaas geen tijd gehad om de hibernate-relation-mappings te zien. 

Wil je de entity houden, mag dat ook. Hieronder de link met meer uitleg. Heel belangrijk is dat je de fetchType op EAGER zet omdat buiten u EJB je niet meer in een transactie bent. Dat leid tot LazyLoading Exceptions.
@JoinColumn(name = "PARK_ID") => Anders maakt hij tussentabellen.
De targetEntity moet je niet zetten, deze is impliciet met je  Definitie van je variable.

http://levelup.lishman.com/hibernate/associations/many-to-one.php

**Comment by h4x0rpr0** [comment]
[Solved] Thanks!
