### ISSUE TITLE
Conversion Error setting value 'Park1' for 'null Converter'.

### ISSUE THREAD

**Issue by r0450086** [2014-OO3/Resort#19]
Als ik in mijn lijst een park wil toevoegen aan mijn bungalow, krijg ik deze error.
Conversion Error setting value 'Park1' for 'null Converter'.
Hoe kan ik dit oplossen?

Branchname: TheMusCATeers

**Comment by luc-steffens-2014** [comment]
Heb je gekeken naar DreamTeam-code, ze hadden gelijkaardige issue en hebben deze ook opgelost. 

https://github.com/2014-OO3/Resort/issues/15

**Comment by r0450086** [comment]
Ja, maar ik vind het verschil niet.
