### ISSUE TITLE
Edit button doesn't edit, it adds (only in customer page)

### ISSUE THREAD

**Issue by r0370288** [2014-OO3/Resort#21]
Bij park en bungalow werkt onze edit knop, enkel bij customer wordt niet overgeschreven maar een nieuwe customer toegevoegd.
We moesten volgende code in commentaar plaatsen: 
(lijn 35 in customer.xhtml)

Dit niet doen, de code dus laten staan, resulteerde in een error waar hij zei dat we een duplicate value aan het creëren waren. 

alvast bedankt

Jasper & Nico

**Comment by luc-steffens-2014** [comment]
Kunnen jullie kijken dat de dao ook merge heeft ipv persist. Dat zal de
duplicate probleem zijn wss
